services:
  booking-system-db:
    image: postgres:16
    container_name: booking_system_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 4001:5432
    volumes:
      - booking_system_data:/var/lib/postgresql/data
    networks:
      - bs

  

volumes:
  booking_system_data:

networks:
  bs: